name: sprint_02
description: "Aplicación Flutter modular organizada por épicas e historias de usuario, con arquitectura basada en principios SOLID. Cada módulo mantiene responsabilidades claras, documentación técnica y separación lógica para facilitar pruebas, integración, mantenimiento y evolución del proyecto sin afectar el código base de cada integrante."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
